export const skillsData = {
  nodes: [
    {
      id: "patryk",
      name: "",
      color: "#FFFFFF",
      type: "decorative",
    },
    {
      id: "css",
      name: "CSS",
      color: "#2465F1",
      type: "fullstack",
    },
    {
      id: "scss",
      name: "SCSS",
      color: "#D06397",
      type: "fullstack",
    },
    {
      id: "tailwind",
      name: "Tailwind",
      color: "#16BDB8",
      type: "fullstack",
    },
    {
      id: "styled-components",
      name: "Styled Components",
      color: "#C363AF",
      type: "fullstack",
    },
    {
      id: "cms",
      name: "CMS",
      color: "#21A3DD",
      type: "decorative",
    },
    {
      id: "wordpress",
      name: "WordPress",
      color: "#21759B",
      type: "cms",
    },
    {
      id: "shopify",
      name: "Shopify",
      color: "#4C822A",
      type: "cms",
    },
    {
      id: "sanity",
      name: "Sanity",
      color: "#F04939",
      type: "cms",
    },
    {
      id: "javascript",
      name: "JavaScript",
      color: "#F0DB4F",
      type: "fullstack",
    },
    {
      id: "typescript",
      name: "TypeScript",
      color: "#007ACC",
      type: "fullstack",
    },
    {
      id: "node",
      name: "Node.js",
      color: "#8CC84B",
      type: "fullstack",
    },
    {
      id: "express",
      name: "Express",
      color: "#FFFFFF",
      type: "fullstack",
    },
    {
      id: "d3",
      name: "D3.js",
      color: "#F47952",
      type: "fullstack",
    },
    {
      id: "react",
      name: "React",
      color: "#00D8FF",
      type: "fullstack",
    },
    {
      id: "redux",
      name: "Redux",
      color: "#764ABC",
      type: "fullstack",
    },
    {
      id: "react-router",
      name: "React Router",
      color: "#F54250",
      type: "fullstack",
    },
    {
      id: "tanstack-query",
      name: "Tanstack Query",
      color: "#FF4154",
      type: "fullstack",
    },
    {
      id: "framer-motion",
      name: "Framer Motion",
      color: "#EF01B9",
      type: "fullstack",
    },
    {
      id: "next",
      name: "Next.js",
      color: "#ffffff",
      type: "fullstack",
    },
    {
      id: "databases",
      name: "DB",
      color: "#21A3DD",
      type: "decorative",
    },
    {
      id: "firebase",
      name: "Firebase",
      color: "#FFCB2C",
      type: "databases",
    },
    {
      id: "supabase",
      name: "Supabase",
      color: "#3ECF8E",
      type: "databases",
    },
    {
      id: "mongodb",
      name: "MongoDB",
      color: "#439934",
      type: "databases",
    },
    {
      id: "prisma",
      name: "Prisma",
      color: "#178C7E",
      type: "databases",
    },
    {
      id: "design",
      name: "Design",
      color: "#21A3DD",
      type: "decorative",
    },
    {
      id: "photoshop",
      name: "Photoshop",
      color: "#355EC9",
      type: "design",
    },
    {
      id: "figma",
      name: "Figma",
      color: "#F24E1E",
      type: "design",
    },
  ],
  links: [
    {
      id: "css-patryk",
      source: "css",
      target: "patryk",
      speed: 1,
      color: "#2465F1",
    },
    {
      id: "scss-css",
      source: "scss",
      target: "css",
      speed: 1,
      color: "#D06397",
    },
    {
      id: "tailwind-css",
      source: "tailwind",
      target: "css",
      speed: 1,
      color: "#16BDB8",
    },
    {
      id: "styled-components-css",
      source: "styled-components",
      target: "css",
      speed: 1,
      color: "#C363AF",
    },
    {
      id: "javascript-patryk",
      source: "javascript",
      target: "patryk",
      speed: 1,
      color: "#F0DB4F",
    },
    {
      id: "react-javascript",
      source: "react",
      target: "javascript",
      speed: 1,
      color: "#00D8FF",
    },
    {
      id: "typescript-javascript",
      source: "typescript",
      target: "javascript",
      speed: 1,
      color: "#007ACC",
    },
    {
      id: "node-javascript",
      source: "node",
      target: "javascript",
      speed: 1,
      color: "#8CC84B",
    },
    {
      id: "express-node",
      source: "express",
      target: "node",
      speed: 1,
      color: "#FFFFFF",
    },
    {
      id: "d3-javascript",
      source: "d3",
      target: "javascript",
      speed: 1,
      color: "#F47952",
    },
    {
      id: "redux-react",
      source: "redux",
      target: "react",
      speed: 1,
      color: "#764ABC",
    },
    {
      id: "react-router-react",
      source: "react-router",
      target: "react",
      speed: 1,
      color: "#F54250",
    },
    {
      id: "framer-motion-react",
      source: "framer-motion",
      target: "react",
      speed: 1,
      color: "#EF01B9",
    },
    {
      id: "tanstack-query-react",
      source: "tanstack-query",
      target: "react",
      speed: 1,
      color: "#FF4154",
    },
    {
      id: "next-react",
      source: "next",
      target: "react",
      speed: 1,
      color: "#FFFFFF",
    },
    {
      id: "cms-patryk",
      source: "cms",
      target: "patryk",
      speed: 1,
      color: "#21A3DD",
    },
    {
      id: "wordpress-cms",
      source: "wordpress",
      target: "cms",
      speed: 1,
      color: "#21759B",
    },
    {
      id: "shopify-cms",
      source: "shopify",
      target: "cms",
      speed: 1,
      color: "#4C822A",
    },
    {
      id: "sanity-cms",
      source: "sanity",
      target: "cms",
      speed: 1,
      color: "#F04939",
    },
    {
      id: "databases-patryk",
      source: "databases",
      target: "patryk",
      speed: 1,
      color: "#21A3DD",
    },
    {
      id: "firebase-databases",
      source: "firebase",
      target: "databases",
      speed: 1,
      color: "#FFCB2C",
    },
    {
      id: "supabase-databases",
      source: "supabase",
      target: "databases",
      speed: 1,
      color: "#3ECF8E",
    },
    {
      id: "mongodb-databases",
      source: "mongodb",
      target: "databases",
      speed: 1,
      color: "#439934",
    },
    {
      id: "prisma-databases",
      source: "prisma",
      target: "databases",
      speed: 1,
      color: "#178C7E",
    },
    {
      id: "design-patryk",
      source: "design",
      target: "patryk",
      speed: 1,
      color: "#21A3DD",
    },
    {
      id: "photoshop-design",
      source: "photoshop",
      target: "design",
      speed: 1,
      color: "#355EC9",
    },
    {
      id: "figma-design",
      source: "figma",
      target: "design",
      speed: 1,
      color: "#F24E1E",
    },
  ],
};
